sudo: false
dist: trusty

language: node_js
node_js:
  - 6

cache:
  yarn: true

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

script:
  - yarn test
  - yarn run lint
